#!/usr/bin/env bash

. "$(dirname -- "${BASH_SOURCE[0]}")/include.sh"
# . include.sh

set -e

declare -A battery_status_icon
battery_status_icon[Discharging]='▶'
battery_status_icon[Charging]='🔌'
battery_status_icon[Not charging]='⚠️'
battery_status_icon[Full]='✔'

cd /sys/class/power_supply/ || exit 255

for d in *; do

    if [ -e "$d/capacity" ] && [ -e "$d/status" ] ; then

        read < "$d/status"
        batstatus="${battery_status_icon[$REPLY]}"
        [ -z "$batstatus" ] && batstatus="$REPLY"

        echo -n "$batstatus"

        read < "$d/capacity"
        blockchart $REPLY 100 ${1:-10}
        echo
    fi
done
