config = [
    {
        "top": 0.05,
        "left": 0.03,
        "margin": 10,
        "maxheight": 0.5,
        "maxwidth": 0.15,
        "title": "agenda",
        "command": ['./tugenda', '--nodate'],
        "outputType": "plaintext",
        "period": 60,
        "fontsize": 16,
        "textColor": [255, 255, 255, 190],
        "bgColor": [0, 0, 0, 30],
    },
    {
        "top": 0.2,
        "title": "priorities",
        "maxwidth": 0.3,
        "command": ['~/wonky/priorities', '3'],
        "outputType": "plaintext",
        "period": 60,
        "align": "topcenter",
        "textAlign": "center",
        "fontsize": 0.014,
        "textColor": [255, 255, 255, 255],
        "bgColor": [0, 0, 0, 30],
        "autoresize": True,
    },
    {
        "top": 0.3,
        "title": "nowgenda",
        "maxwidth": 0.3,
        "command": ['~/wonky/nownow'],
        "outputType": "plaintext",
        "period": 300,
        "align": "topcenter",
        "textAlign": "center",
        "fontsize": 20,
        "textColor": [0, 0, 0, 255],
        "bgColor": [255, 255, 0, 180],
        "autoresize": True,
    },
    {
        "title": "stats",
        "top": 0.03,
        "right": 0,
        "command": ["./system-stats"],
        "period": 4,
        "align": "topright",
        "outputType": "plaintext",
        "textColor": [255, 255, 255, 255],
        "font": "Apple Color Emoji",
        "fontsize": 0.01,
        "textAlign": "right",
        "autoresize": True,
    },
    {
        "align": "middlecenter",
        "outputType": "plaintext",
        "bottom": 0.15,
        "command": ['./weather', '%condition', ],
        "period": 60,
        "font": 'Apple Color Emoji',
        "fontsize": 0.15,
        "textAlign": "center",
        "autoresize": True,
    },
    {
        "align": "middlecenter",
        "outputType": "plaintext",
        "top": 0.03,
        "bottom": 0.15,
        # height=100,
        # width = 400,
        "command": ['./weather',
                    '%feels', '%condition_desc'],
        "period": 60,
        "font": 'bohemian typewriter',
        "fontsize": 30,
        "textAlign": "center",
        "textColor": [127, 127, 127, 255],
        "autoresize": True,
    },
    {
        "align": "bottomcenter",
        "outputType": "plaintext",
        "command": [sys.path[0] +
                    '/weather', '--wonkydetail'],
        "period": 60,
        "bottom": 0,
        #  margin = 30,
        # fontsize=0.012,
        "font": "White Rabbit",
        "textAlign": "center",
        "textColor": [200, 200, 200, 255],
        "autoresize": True,
    },
    {
        "align": "bottomleft",
        "left": 0.03,
        "bottom": 0.05,
        "maxwidth": 0.20,
        "outputType": "html",
        "command": ['./calendar.lua'],
        "period": 300,
        "autoresize": True,
        "fontsize": 16,
    },
    {
        "bottom": 0,
        "align": "bottomcenter",
        "title": "time",
        "command": ["./showtime", "-t",],
        "period": 60,
        "font": "Bohemian Typewriter",
        "fontsize": 0.18,
        "textAlign": "center",
        "textColor": [200, 200, 200, 90],
        "autoresize": True,
        "outputType": "plaintext",
    },
    {
        "top": 0.02,
        "align": "topcenter",
        "title": "date",
        "command": ["/bin/date", "+%A %-d"],
        "period": 60,
        "font": "Bohemian Typewriter",
        "fontsize": 0.1,
        "textAlign": "center",
        "textColor": [255, 255, 255, 90],
        "autoresize": True,
        "outputType": "plaintext",
    },
    {
        "title": "date",
        "top": 0.125,
        "align": "topcenter",
        "command": ["/bin/date", "+%B %Y"],
        "period": 60,
        "font": "Bohemian Typewriter",
        "fontsize": 0.02,
        "textAlign": "center",
        "textColor": [255, 255, 255, 127],
        "outputType": "plaintext",
    },
    {
        "title": "git-status",
        "align": "topright",
        "top": 0.13,
        "right": 0,
        "left": 0.1,
        "period": 45,
        "outputType": "ansi",
        "command": ['./quick-git-status', '--env'],
        "autoresize": False,
    },
]
