#!/usr/bin/env bash

. "$(dirname -- "${BASH_SOURCE[0]}")/include.sh"
# . include.sh

set -e

echo -n '💾'

bc_disk="/"
bc_disk="$(df "$bc_disk" | grep -Po '[0-9\.]+%')"
bc_disk="${bc_disk%'%'}"
bc_disk="${bc_disk%.*}"

blockchart -r "$bc_disk" 100 ${1:-10}

echo
