#!/usr/bin/env bash

. "$(dirname -- "${BASH_SOURCE[0]}")/include.sh"
# . include.sh

set -e

echo -n '💾'

bc_disk="$HOME"
bc_disk="$(df "$bc_disk" | grep -Eo '[0-9\.]+%' | head -n 1)"
bc_disk="${bc_disk%'%'}"
bc_disk="${bc_disk%.*}"

# declare -p bc_disk

blockchart -r "$bc_disk" 100 ${1:-10}

echo
