#!/usr/bin/env bash

. "$(dirname -- "${BASH_SOURCE[0]}")/include.sh"
# . include.sh

set -e

echo -n '💡'

bc_mem=( $(free -t | awk '/^Total:/ {print $2,$3}') )
bc_mem_used=${bc_mem[1]}
bc_mem_total=${bc_mem[0]}

blockchart -r $bc_mem_used $bc_mem_total ${1:-10}

echo
