#!/usr/bin/env bash

priorities_file=~/org/priorities.txt
now_doing="$(tugenda now)"
# now_doing="$(tugenda now | tr '\n' '§' | sed -e 's/§/ \/ /g')"

if [ $# -eq 0 ]; then
   cat - <<EOM >&2

USAGE
   $(basename "$0") [-1] MAXLINES

WHERE
   -1       :   output on one line only [optional]
   MAXLINES :   how many lines to output [mandatory, use 9999 for all
                                         (best I can do for now🙃]
EOM
   exit 255
fi

oneline=false
[ $# -gt 0 ] && [[ "$1" == "-1" ]] && oneline=true && shift
[[ $1 =~ ^[0-9]+$ ]] || die must specify max number of lines to output

doit() {
   if [ -n "$now_doing" ]; then
      echo "${now_doing^^}" | head -n ${1:-3}
   else
      while read -r priority_line; do
         echo "🔘 ${priority_line^^}"
      done <"$priorities_file"
      # cat "$priorities_file" | sed -E 's/^/🔘 /g'
      # cat "$priorities_file" | head -n ${1:-3}
   fi
}

if $oneline; then
   doit "$@" | tr '\n' ' '
else
   doit "$@"
fi
