#!/usr/bin/env bash

set -e

delimiter="\n"

if [ $# -ge 2 ] && [ "$1" == "-d" ] ; then
    delimiter="$2"
    shift
    shift
fi


src_weather_dir=~
src_weather_base=.weather
src_weather="$src_weather_dir/$src_weather_base"
src_weather_current_threshold=15 # mins

src_weather_current="$(fd -g "$src_weather_base" --changed-within ${src_weather_current_threshold}min -uu -d1 "$src_weather_dir" | wc -l)"

if ! [ -e $src_weather_dir/$src_weather_base ] || [ $src_weather_current -eq 0 ]; then

    src_tmp=$(mktemp)

    curl -sm4 'https://wttr.in/?format=location="%l"\ncondition="%c"\ntemperature="%t"\nfeels="%f"\nsunrise="%S"\nsunset="%s"\nhumidity="%h"\nwind="%w"\nprecipitation="%p"\npressure="%P"\ncondition_desc="%C"\nmoon="%m"\n' > $src_tmp

    if [ -s $src_tmp ] ; then
        mv -vf $src_tmp $src_weather
    else
        rm $src_tmp
    fi
fi

. "$src_weather_dir/$src_weather_base"

while [ $# -gt 0 ] ; do

    if [[ "$1" == "%"* ]]; then
        wanted="${1#'%'}"
        output="${!wanted}"

        if [ -n "${output}" ] ; then

            case "$wanted" in
                condition)
                    output="${output%[[:space:]]}"
                    ;;
                sunrise|sunset)
                    output="${output%:*}"
                    ;;
                temperature|feels)
                    output="${output%C}"
                    output="${output#+}"
                    ;;
            esac

            case "${output}" in
                -0°)
                    output="0°"
                    ;;
            esac

            echo -n "${output}|"
        fi
        
    else
        echo -n "${1}"
    fi

    shift
done | tr "|" "$delimiter"

