#!/usr/bin/env bash

set -e

unset w_delimiter

if [ $# -ge 2 ] && [ "$1" == "-d" ]; then
    w_delimiter="$2"
    shift
    shift
fi

if [[ "$(getssid)" == "SKY1EA25"* ]]; then
    weather_location=Greystones
else
    unset weather_location
fi

src_weather_dir=~
src_weather_base=.weather
src_weather="$src_weather_dir/$src_weather_base"
src_weather_current_threshold=15 # mins

src_weather_current="$(fd -g "$src_weather_base" --changed-within ${src_weather_current_threshold}min -uu -d1 "$src_weather_dir" | wc -l)"

if [ $src_weather_current -eq 0 ]; then

    [ -e $src_weather ] && rm $src_weather

    src_tmp=$(mktemp)
    touch $src_tmp

    curl -sm2 'https://wttr.in/'"${weather_location}"'?format=location="%l"\ncondition="%c"\ntemperature="%t"\nfeels="%f"\nsunrise="%S"\nsunset="%s"\ndawn="%D"\ndusk="%d"\nzenith="%z"\nhumidity="%h"\nwind="%w"\nprecipitation="%p"\npressure="%P"\ncondition_desc="%C"\nmoon="%m"\n' >$src_tmp || :

    if [ -s $src_tmp ]; then
        mv $src_tmp $src_weather
    else
        echo "⚠️ unable to retrieve weather data from wttr.in"
        rm $src_tmp
        exit
    fi
fi

. "$src_weather"

condition="${condition%[[:space:]]*}"
sunrise="${sunrise%:??}"
sunset="${sunset%:??}"
dawn="${dawn%:??}"
dusk="${dusk%:??}"
zenith="${zenith%:??}"
feels="${feels%C}"
feels="${feels#+}"
feels="🖐🏻${feels}"
[[ "$feels" == "-0°" ]] && feels="0°"
temperature="${temperature%C}"
temperature="${temperature#+}"
[[ "$temperature" == "-0°" ]] && temperature="0°"
location="${location%,*}"

while [ $# -gt 0 ]; do

    if [[ "$1" == "%"* ]]; then
        wanted="${1#'%'}"
        output="${!wanted}"

        if [ -n "${output}" ]; then
            echo "${output}"
        fi

    elif [[ "$1" == "--wonkydetail" ]]; then
        echo -e "${location}: $condition_desc $feels 🌡$temperature 🌞${dawn}-${sunrise} ${moon}${sunset}-${dusk}"
    else
        echo "${1}"
    fi

    shift

done | while read -r w_item; do
    if [ -n "$w_delimiter" ]; then
        echo -n "$w_item"
        [[ "$w_delimiter" == "false" ]] || echo -n "$w_delimiter"
    else
        echo "$w_item"
    fi
done
